apiVersion: v1
kind: Service
metadata:
  name: learninglog-service
spec:
  type: NodePort
  selector:
    app: learninglog-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 31000